### ISSUE TITLE
Java 9 - java.lang.ClassNotFoundException: org.glassfish.json.JsonProviderImpl 

### ISSUE THREAD

**Issue by C-P-M** [FasterXML/jackson-datatype-jsr353#10]
Caused by: java.lang.ClassNotFoundException: org.glassfish.json.JsonProviderImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at java.json/javax.json.spi.JsonProvider.provider(JsonProvider.java:96)
	... 3 more

Even if the implementation is classpath
org\glassfish\javax.json\1.1\javax.json-1.1.jar

this is module-info.java
    requires jdk.incubator.httpclient;
    requires java.json;

**Comment by cowtowncoder** [comment]
Unfortunately this is not enough to reproduce the issue.

Based on mention of `module-info.java` I assume this would be on JDK version 9 or above?
Perhaps you need to enable something wrt module access.
Might also make sense to try out very latest versions of `javax.json` components; there seems to be `1.1.4`.
